IMPORTING NUMPY

In [ ]:
import numpy as np

Creating Numpy Arrays

In [ ]:
# np.arrays
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
a = np.array([1,2,3], dtype=np.uint8)
print(a)
print(a.dtype)

b = np.array([1,2,3], dtype=complex)
print(b)
print(b.dtype)

[1 2 3]
uint8
[1.+0.j 2.+0.j 3.+0.j]
complex128


In [ ]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
# np.ones and np.zeros
np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np. random
np.random.random((3,4))


array([[0.7633952 , 0.58944555, 0.80943295, 0.77268543],
       [0.15732247, 0.85983092, 0.1440634 , 0.02493646],
       [0.7585617 , 0.54311301, 0.93457312, 0.92099032]])

In [ ]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# ndim
a3.ndim

3

In [ ]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# item size
a3.itemsize

8

In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


Changing Datatype

In [ ]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Opration

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# scalr operations
#arithmatic
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
#relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector oprations
# arithmatic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

Array Function

In [ ]:
a1=np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[34., 20., 16.],
       [21., 14.,  5.],
       [66., 23., 72.]])

In [ ]:
# max/min/sum/prod
# 0-> col and 1-> row
np.prod(a1,axis=0)

<>:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-88-26735a392b34>:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a1=np.array([[1,2][3,4]])


TypeError: list indices must be integers or slices, not tuple

In [ ]:
# mean /median/std/var
np.var(a1,axis=1)

array([ 59.55555556,  42.88888889, 476.22222222])

In [ ]:
# trigonometric function
np.sin(a1)

array([[ 0.52908269,  0.91294525, -0.28790332],
       [ 0.83665564,  0.99060736, -0.95892427],
       [-0.02655115, -0.8462204 ,  0.25382336]])

In [ ]:
# Angle array in degrees
angles_deg = np.array([0,30,45,60,90])
# convert to radians
angles_rad = np.deg2rad(angles_deg)


print("Angles in degrees:" ,angles_deg)
print("Angles in radians:",angles_rad)

print("sine:",np.sin(angles_rad))
print("cosine:",np.cos(angles_rad))
print("tangent:",np.tan(angles_rad))

Angles in degrees: [ 0 30 45 60 90]
Angles in radians: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
sine: [0.         0.5        0.70710678 0.8660254  1.        ]
cosine: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("a:",a)

print("b:",b)

print("c:",c)





a: [1.9 2.  3. ]
b: [[1 2]
 [3 4]]
c: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
a.ndim

1

In [ ]:
b.ndim


2

In [ ]:
c.dim

3

In [ ]:
a.shape

(3,)

In [ ]:
b.shape

(2, 2)

In [ ]:
c.shape

(2, 2, 2)

In [ ]:
a.size

3

In [ ]:
b.size

4

In [ ]:
c.size

8

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('int64')

In [ ]:
c.dtype

dtype('int64')

In [ ]:
a.itemsize

8

In [ ]:
b.itemsize

8

In [ ]:
c.itemsize

8

In [ ]:
a.nbytes

24

In [ ]:
b.nbytes

32

In [ ]:
c.nbytes

64